colors:
  - Insignificant
  - White
  - Red
  - Orange
  - Yellow
  - Green
  - Blue
  - Lavender
  - Pink
  - Purple
  - Brown
  - Not applicable

sun_lights:
  - Full sun
  - Partial shade
  - Full shade

soils:
  - Clay
  - Loam
  - Silt
  - Sandy
  - Wide range
  - Well-drained
  - Water-retentive

soil_ph:
  - Acidic
  - Neutral
  - Alkaline
  - Wide-range